Update exodus-lambda-deploy DistributionConfig [RHELDST-8908]
release-engineering/exodus-lambda pull request #317
Opened 2022-02-01 21:13 UTC by negillett

As ForwardedValues is deprecated this commit implements a CachePolicy
and replaces ForwardedValues with CachePolicyId.

2022-02-01 21:15 UTC, negillett reviewed
I've ensured that this is deployable:
https://console.aws.amazon.com/codesuite/codepipeline/pipelines/ngillett-pipeline-dev/view?region=us-east-1

2022-02-02 03:27 UTC, rohanpm requested changes

2022-02-02 03:27 UTC, rohanpm commented on configuration/exodus-lambda-deploy.yaml
> +        Name: !Sub ${project}-cache-policy-${env}
I do think they should be changed:

For MinTTL, I think it should be 0.  I'm reading this table here - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationDownloadDist , and the "Minimum TTL = 0 seconds" sounds like the behavior we want.

In particular, if MinTTL isn't 0 then adjusting max_age in lambda_config.json to a value less than MinTTL won't work, so we'd have to always pay attention to ensure we keep those two bits synchronized.  Also it breaks Cache-Control: no-cache entirely, which we don't use now but we might need to later.

As for DefaultTTL and MaxTTL, are you sure it's required to set them?  I'm looking at https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CachePolicyConfig.html and it says only MinTTL is needed.  I would be in favor of omitting Default and Max if that's able to work.  If they are really required, they should be set to a much higher value, maybe just copying the values out of those docs.  600 seconds is meant to be our "short" TTL for files which can be modified at any time, like repomd.xml, but for the vast majority of URLs we want to cache for much longer and the defaults look OK.

2022-02-02 16:01 UTC, negillett commented on configuration/exodus-lambda-deploy.yaml
> +        Name: !Sub ${project}-cache-policy-${env}
That's strange. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachepolicy-cachepolicyconfig.html says they are required.
Also, I got the following error when attempting to deploy without name and default, min, max TTL:
> #/CachePolicyConfig: required key [Name] not found (#/CachePolicyConfig)
#/CachePolicyConfig: required key [MinTTL] not found (#/CachePolicyConfig)
#/CachePolicyConfig: required key [MaxTTL] not found (#/CachePolicyConfig)
#/CachePolicyConfig: required key [DefaultTTL] not found (#/CachePolicyConfig)"

I'll try again with just MinTTL to be sure.

2022-02-02 16:05 UTC, negillett commented on configuration/exodus-lambda-deploy.yaml
> +        Name: !Sub ${project}-cache-policy-${env}
Yeah...

> "Model validation failed (#/CachePolicyConfig: 3 schema violations found)
#/CachePolicyConfig: required key [Name] not found (#/CachePolicyConfig)
#/CachePolicyConfig: required key [MaxTTL] not found (#/CachePolicyConfig)
#/CachePolicyConfig: required key [DefaultTTL] not found (#/CachePolicyConfig)"

2022-02-02 16:07 UTC, negillett commented on configuration/exodus-lambda-deploy.yaml
> +        Name: !Sub ${project}-cache-policy-${env}
Events with those errors can be seen at https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/events?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A333296168829%3Astack%2Fngillett-lambda-dev%2F21dff200-5e97-11ec-9d80-0eae5f7c52eb

2022-02-02 16:07 UTC, negillett commented on configuration/exodus-lambda-deploy.yaml
> +        Name: !Sub ${project}-cache-policy-${env}
I've updated these fields with the documented default values.

2022-02-02 22:25 UTC, rohanpm approved these changes

2022-02-03 00:08 UTC, merged