Add "X-Exodus-Query" header
release-engineering/exodus-lambda pull request #338
Opened 2022-04-07 14:53 UTC by dichn

Because of the traffic shift and traffic will be routed to different
lambda versions (in different regions), integration tests may run again
an old version lambda.

The "X-Exodus-Query" header is primarily used in a request, to provide
the version of exodus-lambda, "X-Exodus-Version" in response.

For traffic shift:
https://aws.amazon.com/blogs/compute/implementing-safe-aws-lambda-deployments-with-aws-codedeploy/

2022-04-07 23:17 UTC, dichn commented
re-push for fixing a typo in commit message (no code change)

2022-04-08 00:07 UTC, rohanpm requested changes
I think the commit message is misleading:

- this has nothing to do with
https://aws.amazon.com/blogs/compute/implementing-safe-aws-lambda-deployments-with-aws-codedeploy/ , which is not something we're using or will be able to use
- I don't think "Because of the traffic shift and traffic will be routed to different
lambda versions (in different regions)" is correct.  At best it's misleading to say this is because of "traffic shift" and then link to an article about a kind of traffic shifting we're not doing.

Could the commit message please stick with the known facts?  You don't have to put forward a theory as to why we might be hitting an old version of the lambda sometimes.

I would have written something like "Our tests sometimes seem to hit an old version of our lambda, for unclear reasons. Let's make it possible to query the currently deployed lambda version so we can at least reliably detect when this happens."

2022-04-08 00:07 UTC, rohanpm commented on exodus_lambda/functions/origin_response.py
> +            self.logger.error("x-exodus-query exist")
Please drop this as it's not an error.  You could keep a debug() if you really need it.

2022-04-08 02:48 UTC, dichn commented
1) commit message updated
2) remove useless log

2022-04-08 04:01 UTC, rohanpm submitted a review, later dismissed

2022-04-08 05:48 UTC, dichn commented
re-push after the rebase of #337

2022-04-08 13:13 UTC, crungehottman approved these changes

2022-04-09 00:12 UTC, merged